project_dir: test_results
data_dir: example_data
rsID_map_file: example_data/rsID_map_example.txt
main_gwas_file: example_data/clustering_data_sources_example.xlsx
pval_cutoff: 5e-8
ref_pop: "EUR"
r2: 0.05
maf: 0.001
chromosomes: "1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22"
missing_cutoff: 0.8
proxy_search_method: "LDlink"
pval_cutoff2: 0.05
fill_missing_method: "median"
cor_cutoff: 0.8
n_bnmf_reps: 25
bnmf_tolerance: 1e-6


